name: Android Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install cython

      - name: Build APK
        env:
          ANDROIDSDK_ACCEPT_LICENSE: "1"
          OPCAO_FALA: "ativada"
          CHAVE_ACESSO_IA: "obrigatoria"
        run: |
          echo "OPCAO_FALA=$OPCAO_FALA" >> $GITHUB_ENV
          echo "CHAVE_ACESSO_IA=$CHAVE_ACESSO_IA" >> $GITHUB_ENV
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DirectorAI-APK
          path: bin/*.apk
